# Wright a program :
print(" ")
print("Intput...")
print(" ")
a = int(input("Enter your roll number : "))
b = input("Enter your name : ")
c = int(input("Enter your English marks : "))
d = int(input("Enter your Maths marks : "))
e = int(input("Enter your Science marks : "))
f = c+d+e
print(" ")
print("Output...")
print(" ")
print("-"* 80)
print("\t\t\t\tStudent Report")
print("-"* 80)
print("\t. Roll no : ",a )
print("\t. Name   : ",b )
print("\t. Eng       : ",c )
print("\t. Maths  : ",d )
print("\t. Sci         : ",e )
              
print("\t. Total marks : ",f)
print("\t. AVG : ",f/3)
print("-"* 80)
print("-"* 80)

input()
