#Draw a snowman:

import turtle

t = turtle.Pen()
s = turtle.Screen()
s . bgcolor("black")
s . setup(900,700)
t . speed(0)
t . color("white")
t . width(5)
t . up()
t . forward(100)
t . down()
t . left(90)
t . up()
t . forward(100)
t . down()
t . color("black","white")
t . begin_fill()
t . circle(100,630)
t . end_fill()
t . left(90)
t . up()
t . forward(150)
t . down()
t . left(90)
t . up()
t . forward(50)
t . down()
t . color("black","white")
t . begin_fill()
t . circle(9)
t . end_fill()
t . up()
t . backward(100)
t . down()
t . color("black","white")
t . begin_fill()
t . circle(9)
t . up()
t . forward(60)
t . down()
t . left(90)
t . up()
t . forward(50)
t . down()
t . end_fill()
t . color("black","white")
t . begin_fill()
t . circle(9,450)
t . end_fill()
t . right(90)
t . up()
t . forward(60)
t . down()
t . left(90)
t . circle(70,50)
t . left(180)
t . circle(-70,100)
t . left(180)
t . circle(70,50)
t . right(90)
t . up()
t . forward(30)
t . down()
t . color("black","white")
t . begin_fill()
t . right(90)

t . circle(150)
t . left(90)
t . up()
t . forward(50)
t . down()
t . circle(5)
t . up()
t . forward(50)
t . down()
t . circle(5)
t . up()
t . forward(50)
t . down()
t . circle(5)
t . up()
t . forward(50)
t . down()
t . circle(5)
t . up()
t . forward(50)
t . down()
t . circle(5)
t . up()
t . backward(450)
t . down()

t . backward(50)
t . circle
t . end_fill()


input()


