# Draw a Rainbow:

import turtle

a = turtle.Pen()
scr = turtle.Screen()
scr . setup(1200,600)
scr . bgcolor("black")
a . speed(4)
a . width(30)

a . up()
a . forward(150)
a . down()

a . color("red")
a . begin_fill()
a . left(90)
a . circle(200,180)
a . left(90)
a . end_fill()
a . up()
a . forward(370)
a . down()

a . color("orange")
a . begin_fill()
a . left(90)
a . circle(174,180)
a . left(90)
a . end_fill()
a . up()
a . forward(320)
a . down()

a . color("yellow")
a . begin_fill()
a . left(90)
a . circle(148,180)
a . left(90)
a . end_fill()
a . up()
a . forward(270)
a . down()

a . color("green")
a . begin_fill()
a . left(90)
a . circle(122,180)
a . left(90)
a . end_fill()
a . up()
a . forward(220)
a . down()

a . color("purple")
a . begin_fill()
a . left(90)
a . circle(96,180)
a . left(90)
a . end_fill()
a . up()
a . forward(170)
a . down()

a . color("cyan")
a . begin_fill()
a . left(90)
a . circle(76,180)
a . left(90)
a . end_fill()
a . up()
a . forward(120)
a . down()

a . color("pink","black")
a . begin_fill()
a . left(90)
a . circle(50,180)
a . left(90)
a . end_fill()
a . up()
a . forward(70)
a . down()
a . hideturtle()


input()
